### ISSUE TITLE
testing of division function 

### ISSUE THREAD

**Issue by 99003515** [99003512/SDLC_Calculator#33]
division function supposed to have 2 test cases only one is tested 
![div](https://user-images.githubusercontent.com/78543049/109459010-f2ef3700-7a83-11eb-918c-162315fee826.png)
![division](https://user-images.githubusercontent.com/78543049/109459012-f4206400-7a83-11eb-9a6a-47c34c66c58f.png)

**Comment by 99003513** [comment]
another test case is done in the main function
