### ISSUE TITLE
Team 2_ Review_Outcome

### ISSUE THREAD

**Issue by 99003578** [99003512/SDLC_Calculator#60]
1. Warnings for implicit declarations
![Screenshot from 2021-03-01 16-43-39](https://user-images.githubusercontent.com/78539913/109491079-24312c80-7aaf-11eb-9103-0bf14b6ddec7.png)

2. code exiting with error
![Screenshot from 2021-03-01 16-54-54](https://user-images.githubusercontent.com/78539913/109491046-1b405b00-7aaf-11eb-8453-dfa659ced7c8.png)

**Comment by 99003512** [comment]
Rectified.
